language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install coveralls
# command to run tests
script: nosetests --with-coverage --cover-package=ttpassgen
after_success:
  coveralls